# Generated by Django 3.1.5 on 2021-07-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='size',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size_id',
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_id',
            field=models.ManyToManyField(to='Core.Size'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.product'),
        ),
    ]
