# Generated by Django 3.1.5 on 2021-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210707_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_name',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.FileField(default='no_photo.jpg', upload_to='ProductImages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
